import 'package:flutter/material.dart';
Color mainBackground = const Color.fromARGB(255, 248, 250, 255);
Color iconBackgroundColor = const Color.fromARGB(255, 102, 153, 255);
Color tagBackgroundColor = const Color.fromARGB(255, 55, 106, 237);
Color drawerBackground = const Color.fromARGB(205, 68, 76, 91);
Color white = Colors.white;
Color blue = Colors.blue;
Color grey = Colors.grey.shade300;
Color grey2 = Colors.grey.shade200;
Color black = Colors.black;
Color transparent = Colors.transparent;
Color starYellow = Colors.orangeAccent;
